export const TYPE = {
  LIKE_NUMBER: 'LIKE_NUMBER',
  FONT_NUMBER: 'FONT_NUMBER',
  UPDATE_COMMENT:'UPDATE_COMMENT',
  // Example 3: Cart
  ADD_TO_CART: 'ADD_TO_CART',
  DEL_PROD_CART: 'DEL_PROD_CART',
  UP_DOWN_PROD_CART: 'UP_DOWN_PROD_CART',
}